puts "The students of my cohort at Makers Academy"
puts "Berta"
puts "Megan"
puts "Roland"
puts "James"
puts "Abraham"
puts "Roy"
puts "Jorja"
puts "Colin"
puts "Ayaz"
puts "Kalle"
puts "Andrey"
puts "Biwek"
puts "Mihai-Liviu"
puts "Makis"
puts "Nabin"
puts "Peter"